<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Lightbox "Fancybox"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>FancyBox is a tool for displaying images, html content and multi-media in a Mac-style "lightbox" that floats overtop of web page. It was built using the jQuery library.</p>
    <p>Сайт: <a target="_blank" href="http://fancybox.net/">http://fancybox.net</a></p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Customizing widget "Fancybox"</a></li>
    </ul>
</article>