<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Лайтбокс "Fancybox"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>FancyBox — это инструмент для отображения изображений, HTML-контента и мультимедиа в «лайтбоксе» в стиле Mac, который отображается поверх веб-страницы.
Применяется с использованием библиотеки jQuery с возможностью подключения плагинов.</p>
    <p>Сайт: <a target="_blank" href="http://fancybox.net/">http://fancybox.net</a></p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Настройка виджета "Fancybox"</a></li>
    </ul>
</article>